version: '3.7'
services:
  mysql-service:
    image: mysql:8.0.19
    volumes:
      - ./data/:/var/lib/mysql/
      - ./schema/:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=alex
      - MYSQL_PASSWORD=E7PgwDjz